### ISSUE TITLE
IDE Integration and Support

### ISSUE THREAD

**Issue by sirinath** [adept-dm/adept#25]
Hi,

Is it possible to have tighter and seamless IDE integration. Also perhaps package with Scala IDE also.

Suminda

**Comment by freekh** [comment]
Yeah I agree that IDE integration would be nice. I think the buildtools implementing Adept (sbt hint hint) should be more or less responsible for it providing you actually use a build tool. Perhaps you are saying that it would be cool to have because you might not really need a build tool in the case where adept manages your dependencies and I agree with that :)
So it is definitely interesting and something to have in the back of our heads, but I think Adept has to mature (ie at least have a end to end working implementation:) a bit before we can dive into it. 

Suminda Dharmasena notifications@github.com wrote:

> Hi,
> 
> Is it possible to have tighter and seamless IDE integration. Also
> perhaps package with Scala IDE also.
> 
> Suminda
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adept-dm/adept/issues/25

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
